### ISSUE TITLE
$this->ci->having implementation

### ISSUE THREAD

**Issue by arisdario** [IgnitedDatatables/Ignited-Datatables#112]
Hello, i'm trying to make some complex query but i'm facing some issues.

I think i need to extend the get_total_results function to get a correct result but...

If i do: 

  `$this->datatables->select('cities.city_code, cities.city_name, SUM(bulbs.qty) as totalQty')->join('bulbs', 'bulbs.city_code=cities.city_code', 'left')->from('cities')->where('city', 'New York')->having('totalQty <>', '0');`
 it will return me an error like: `Unknown column 'totQty' in 'having clause'`

That's because datatables perform a SELECT \* instead the columns i declared, so i think from here the issue.
Is there a way to get this query working with Ignited-Datatables ?

**Comment by Allan-Nava** [comment]
I add `COUNT(*)` and `SUM(a.price`) but doesn't work the where clause for dates. 
How can I fix?

**Comment by fartymonk** [comment]
I also have this problem, but I solved it by modifying the `get_total_results()` a bit, to add this lines right at the beginning of the function.

```
if(!empty($this->select)) {
            foreach ($this->select as $col => $cond) {
                $this->ci->db->select($cond.' as ' . $col);
            }
        }
```
