### ISSUE TITLE
Callbak URL Serialize Encrypt add_column or edit_column

### ISSUE THREAD

**Issue by jafarsidik** [IgnitedDatatables/Ignited-Datatables#131]
Hallo, 

How to create code this Output URL :
http://localhost/cms/content/form/JDE=

This Existing Code, doesn't Not works serialize in loop data.
Controller : 

      public function load()
	{
		$this->datatables->select('c.id as id, c.code as code');

		$this->datatables->from('cms_content c');

		$this->datatables->add_column('edit', $this->callback_url('$1'), 'id');
		
		echo  $this->datatables->generate();
	}

	function callback_url($params) {

		return site_url('cms/content/form/').base64_encode($params);
		
	}

**Comment by digitaloutback** [comment]
I would do it like this:

```
public function load()
{
    function callback_url($id) {
        return site_url('cms/content/form/').base64_encode($id);
    }
    $this->datatables->add_column('edit', '$1', "callback_url(id)");
}
```

**Comment by jafarsidik** [comment]
hallo Sir @digitaloutback ,

Thx Before, Your Code Is Working. 👍 👍 👍
