### ISSUE TITLE
Cant Use this Library with current Datatable version

### ISSUE THREAD

**Issue by arhen** [IgnitedDatatables/Ignited-Datatables#133]
For datatables above 1.10 , almost every paramater that sent to server via ajax Datatables has been renamed. 
like 
in this library using sSearch but, from now, datatables just using 'search'

**Comment by n1crack** [comment]
I didn’t see sSearch being used.  It is updated 4 years ago. 

https://github.com/IgnitedDatatables/Ignited-Datatables/commit/a1cd0cb2d3c0ae7c73c211bb3864ae09dba758fe

**Comment by foxmedo** [comment]
im using this lib with datatables "1.10.12" and it's working well

**Comment by foxmedo** [comment]
if you have any issue you can share it with us

**Comment by arhen** [comment]
Sorryr, im outdate about the library
