### ISSUE TITLE
custom GROUP BY

### ISSUE THREAD

**Issue by Mexx77** [IgnitedDatatables/Ignited-Datatables#27]
Hi,

I need custum GROUP BY functionality so I added this function to Datatables.php
Unfortunately, the total results are then incorrect (result is alway 1). How can I resolve this, such that the correct number of rows is displayed?

Thanks, Max

```
/**
* Generates a custum GROUP BY portion of the query
*
* @param string $val
* @return mixed
*/
public function group_by($val)
{
   $this->group_by[] = $val;
   $this->ci->db->group_by($val);
   return $this;
}
```

I added to lines to get_total_results():

```
foreach($this->group_by as $val)
        $this->ci->db->group_by($val);
```

and added at the top an array:

```
protected $group_by       = array();
```

But now I always get 1 as a result... ?

**Comment by Allan-Nava** [comment]
The group_by works with where clasues?
