### ISSUE TITLE
GROUP_CONCAT in filter error

### ISSUE THREAD

**Issue by kingjia90** [IgnitedDatatables/Ignited-Datatables#43]
hi,

here is the fix i have add to make group concat working:

```
public function select($columns, $backtick_protect = TRUE)
{
  foreach($this->explode(',', $columns) as $val)
  {

    /*GROUP CONCAT FIX JJ*/
    $finder = strpos($val,"GROUP_CONCAT");

    $column = trim(preg_replace('/(.*)\s+as\s+(\w*)/i', '$2', $val));
    $this->columns[] =  $column;
    if ($finder!==false){
      $this->select[$column] =  trim(preg_replace('/(.*)\s+as\s+(\w*)/i', '$2', $val));
    }else{
      $this->select[$column] =  trim(preg_replace('/(.*)\s+as\s+(\w*)/i', '$1', $val));
    }
  }
```

mysql ...GROUP_CONCAT(codice,"") as center...

Before this fix, the filter where using the search on the function istead of the "as" value, 
pratically were: group_concat(codice,"") like %finding%
while i needed
center like %finding%

Hope this will help somebody, maybe you can reintegrate the source with a better coding

J

**Comment by pakistanihaider** [comment]
Is there any other better option. 
Cuz when used group_concat, then search is only done in concanated string, not in other columns :(

**Comment by n1crack** [comment]
try subqueries when using group functions.
