### ISSUE TITLE
group_by and order_by don't work when I use both in a query

### ISSUE THREAD

**Issue by techjewel** [IgnitedDatatables/Ignited-Datatables#49]
At first, Thanks for a wonderful library. I have a situation where I have to join 2 table and I have to use join and group_by function to join with the latest row of a group of rows.

But when I try to use that don't work.

Would you please give me a solution of that.

Thanks

**Comment by putul** [comment]
you can do it by using this
$this->db->order_by('column_name','asc/desc');
