### ISSUE TITLE
get_total_results very slow on large tables

### ISSUE THREAD

**Issue by andrejflorjancic** [IgnitedDatatables/Ignited-Datatables#69]
I propose the following changes:

if(strlen($this->distinct) > 0)
{
    $this->ci->db->distinct($this->distinct);
    $this->ci->db->select($this->columns);

```
$query = $this->ci->db->get($this->table, NULL, NULL, FALSE);
return $query->num_rows();
```

}
else 
{
    $this->ci->db->select('count(0) num_rows');
    $query = $this->ci->db->get($this->table, NULL, NULL, FALSE);

```
$res = $query->result();
return $res[0]->num_rows;
```

}

**Comment by zazikhan** [comment]
I am searching for the same solution i have 70,000 rows but it takes seven to eight secs to display the results

**Comment by arisdario** [comment]
I will suggest for a limit and remove the informational Showing 1 to 100 of 96,451 entries for me it takes 3.4secs to load the information, but removing the "of 96,451 entries" it load in 1.3secs.

**Comment by zazikhan** [comment]
please share your code @arisdario cause i thought the same of removing the lable "70,000 entries" and it will work fine
