### ISSUE TITLE
add_column does not work

### ISSUE THREAD

**Issue by ilzat** [IgnitedDatatables/Ignited-Datatables#79]
Hello, i used to:

            $this->datatables
                    ->select('objects.id, objects.creator_id, objects.obj_name_short')
                    ->from('objects')
                    ->join('users','users.id=objects.creator_id','left')
                    ->select('surname')
                    ->add_column('buttons', 'Hello World');
            echo $this->datatables->generate();

table loading, but does not work when searching
error output:

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: buttons</p>
<p>Filename: libraries/Datatables.php</p>
<p>Line Number: 322</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at Z:\home\sd2\www\system\core\Exceptions.php:185)</p>
<p>Filename: core/Common.php</p>
<p>Line Number: 440</p>

And My JS code:
$(document).ready(function() {
	$('#datatable').dataTable( {
		"processing": true,
		"serverSide": true,
		"ajax": {
		  "url": "/dashboard/getObjectsByAjax",
      "type": "POST"
      },
    "columns": [
			{ "data": "id" },      
			{ "data": "creator_id" },
      { "data": "obj_name_short" },
      { "data": "surname" },
      { "data": "buttons" }
		] 
    
	} );
} );

please help me

**Comment by h34v3n** [comment]
$this->datatables
                ->select('objects.id, objects.creator_id, objects.obj_name_short')
                ->from('objects')
                ->join('users','users.id=objects.creator_id','left')
                ->select('surname') <---- you are using this one for??
                ->add_column('buttons', 'Hello World'); <--- 
        echo $this->datatables->generate();


I am showing an example to use add_column
->add_column('acciones', '$1', "cuentas.id"

maybe this can help you

**Comment by aazbeltran** [comment]
1 year later... I solved this issue modifying the conditional on [L313](https://github.com/IgnitedDatatables/Ignited-Datatables/blob/master/application/libraries/Datatables.php#L313)

```php
if ($mColArray[$i]['searchable'] == 'true' && !array_key_exists($mColArray[$i]['data'], $this->add_columns)){
```
