### ISSUE TITLE
replace parameter in add_column/edit_column

### ISSUE THREAD

**Issue by iMezied** [IgnitedDatatables/Ignited-Datatables#86]
I try to use function within add_column/edit_column
I created function "getDays($date)" in helper and import helper
when I try to pass parameter to the function it return the name of column as string not as value 
$this->datatables->edit_column('lastModified','$1','getDays(lastModified)');
so the lastModified as name replaces $1 not the value of lastModified

**Comment by h34v3n** [comment]
I guess when you are editing a column is because the column already exists, so i named like the field that i want to change.

->edit_column('cuentas.tipo_cuenta', '
     <span class="label label-$1"> $2</span>
     ', 
    'color_tipo(cuentas.tipo_cuenta), tipo_cuenta(cuentas.tipo_cuenta)' 
)
the helper looks like the sintaxis is working but you didnt put the getDays function.

**Comment by n1crack** [comment]
https://github.com/IgnitedDatatables/Ignited-Datatables/issues/50#issuecomment-412293607
