### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by gpgabrielpaiva** [IgnitedDatatables/Ignited-Datatables#88]
My search not working :(

$("#tabela_ecommerce").dataTable({
        "processing": true,
        "serverSide": true,
        "sServerMethod": "POST",
        "sAjaxSource": "<?= base_url(); ?>projeto/ajaxCarregarProdutos",
        "fnServerData": function (sSource, aoData, fnCallback) {
                        $.ajax
                        ({
                            "dataType": "json",
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
        },  
        "aoColumns": [
        {"mData": "imagem_produto", "sClass": "text-center"},
        {"mData": "codigo_produto", "sClass": "text-center", "bSearchable": true},
        {"mData": "nome_produto", "bSearchable": true},
        {"mData": "quantidade_produto", "sClass": "text-center"},
        {"mData": "valor_produto"},
        {"mData": "selecionar_produto", "sClass": "text-center"}
        ]
    });

**Comment by gpgabrielpaiva** [comment]
Is showing, just is not working the search.

**Comment by fipsofant** [comment]
You found a solution?

**Comment by gpgabrielpaiva** [comment]
No, I used my knowledge with jQuery and made its own search.
