### ISSUE TITLE
order by

### ISSUE THREAD

**Issue by marikudo** [IgnitedDatatables/Ignited-Datatables#93]
Hi, I tried to use ->order_by(), think is not working..

Thanks

**Comment by olimortimer** [comment]
You might want to expand as to why it isn't working, and what you've tried.

**Comment by marikudo** [comment]
I have tried ordering the way CI to order but it not working. but anyway i found fixes here
https://github.com/IgnitedDatatables/Ignited-Datatables/issues/63

Thanks..
