### ISSUE TITLE
edit column helper class display the button when the User allowed

### ISSUE THREAD

**Issue by tiegosilveira** [IgnitedDatatables/Ignited-Datatables#99]
display the button when the User is allowed

when if it is equal "211" displays

$this->datatables->set_database('webgpon');//banco
        $this->datatables->select('llids.id,llid,llids.observacoes,onus.idOLT,login,macAddress,olts.nome')
        ->from('llids')
        ->join('onus', 'llids.idONU = onus.id','left')//join
        ->join('olts', 'onus.idOLT = olts.id','left')//join
        ->edit_column('altera', '$1', $this->status('id'))
        ->add_column('deleta', anchor('webgpon/deleta_llid/$1','
                <button class="btn btn-primary btn-xs" 
                    title="Deleta">
                    <span class="glyphicon glyphicon-edit"> Deleta</span>
                </button>'), 
            'id'); 
        echo $this->datatables
##             ->generate("json");

helper class
   function status($id)
    { 
        if($id == '211'){
            $output = "<a class='btn btn-default btn-xs'  
                                  href='altera_llid'".$id."'>
                                  <span class='glyphicon glyphicon-edit'> Altera</span>
                            </a>";
        }else{
             $output = ""
        }
     return $output;
    }

**Comment by marikudo** [comment]
Same Problem here, timelog_date is datetime datatype and  I want to change the format. 

 $this->datatables->select('id,timelog_date')
        ->edit_column('timelog_date','$1',date("l F j, Y",strtotime('timelog_date')))
        ->from('tblname');

**Comment by foxmedo** [comment]
any one has  find a solution for this problem

**Comment by n1crack** [comment]
Your syntax is wrong. The way you use the library is possible but needs some modifications which I already have done in my repo. 

Currently you can try: 
‘’’’
$this->datatables->select('id,timelog_date')
->edit_column('TestCol','$1',”custom(param,TestCol)”)
->from('tblname');
‘’’’

**Comment by foxmedo** [comment]
but how can i put in the place of param an array ?

**Comment by foxmedo** [comment]
FYI 

i have solve the problem using the json as args
